# Unified FeastFinder Local Development Stack
# Includes full backend microservices stack & launches Frontend with Vite Hot-Module-Reloading (HMR)

include:
  - backend/docker-compose.yaml

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    image: ghcr.io/weishenl/g4t4-is213-frontend:latest
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/index.html:/app/index.html
    env_file:
      - ./frontend/.env
    restart: always
    networks:
      - feastfinder-network
    depends_on:
      - kong
